# =============================================================================
# Streamlit Configuration - Corporate Environment Optimized
# =============================================================================
# This configuration is optimized for corporate browsers with strict security
# policies that may block WebSockets, aggressive JavaScript, or auto-updates.
# =============================================================================

[server]
# Use polling instead of WebSocket for better corporate firewall compatibility
enableWebsocketCompression = false
enableXsrfProtection = false

# Reduce aggressive connection behavior
maxUploadSize = 50
maxMessageSize = 50

# Port configuration (default: 8501)
port = 8501
headless = true

# File watching disabled for production stability
fileWatcherType = "none"

# CORS settings for localhost development
enableCORS = false

[browser]
# Disable auto-open (annoying in corp environments)
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

[runner]
# Less aggressive refresh behavior
magicEnabled = false
fastReruns = false

# Reduce script rerun overhead
postScriptGC = true

[client]
# Corporate-friendly client settings
showErrorDetails = true
toolbarMode = "minimal"

# IMPORTANT: Disable connection status overlay (the gray banner you mentioned!)
# This is what causes the 30-second freeze in strict security environments
showSidebarNavigation = true

[theme]
# Customer Branding: Wells Fargo
# Wells Fargo Red: #D71E28 (official brand color)
# Using Wells Fargo red for primary interactive elements and header accents
base = "light"
primaryColor = "#D71E28"  # Wells Fargo Red - used for buttons, links, accents
backgroundColor = "#FFFFFF"  # Clean white background
secondaryBackgroundColor = "#F0F2F6"  # Light gray for cards/sections
textColor = "#262730"  # Dark gray for readability
font = "sans serif"

[logger]
# Reduced logging for production
level = "error"
messageFormat = "%(asctime)s %(message)s"

# =============================================================================
# CORPORATE ENVIRONMENT NOTES
# =============================================================================
# If dashboard still freezes:
# 1. Check if WebSockets are blocked by corporate proxy
# 2. Try accessing via corporate VPN vs direct network
# 3. Ask IT to whitelist localhost:8501 in browser security policies
# 4. Consider deploying behind corporate reverse proxy (nginx/apache)
# 5. Test with different browser (Edge often works better in corporate env)
# =============================================================================
