# Streamlit Secrets Configuration
# This file contains sensitive configuration values
# DO NOT commit this file to version control!

[daemon]
# API key for TFT Inference Daemon authentication
# This key must match the TFT_API_KEY environment variable on the daemon
api_key = "TeuOYlzXVSPxxTLghBBUyhOM5aT9dhY302QcG0vwEaqq6cY5vycuLBzntHvbFnmf"

# Production deployment notes:
# 1. Set this same key in your daemon environment: export TFT_API_KEY="..."
# 2. This file is automatically managed by generate_api_key.py
# 3. The start scripts will automatically set the environment variable
